# This file was generated by GoReleaser. DO NOT EDIT.
class Ldget < Formula
  desc "A simple command line interface tool to get RDF items using HTTP GET requests."
  homepage "https://github.com/ontola/ldget"
  url "https://github.com/ontola/ldget/releases/download/v0.1.5/ldget_0.1.5_Darwin_x86_64.tar.gz"
  version "0.1.5"
  sha256 "7fe96e3949fbd5674adeb86a7b3e7e345c2cfc710e06e011ec23bb8ad0f96075"

  def install
    bin.install "ldget"
  end
end
