# This file was generated by GoReleaser. DO NOT EDIT.
class Ldget < Formula
  desc "A simple command line interface tool to get RDF items using HTTP GET requests."
  homepage "https://github.com/ontola/ldget"
  url "https://github.com/ontola/ldget/releases/download/v0.1.2/ldget_0.1.2_Darwin_x86_64.tar.gz"
  version "0.1.2"
  sha256 "dcccd23dc2b7a3e232dbb6ac70e47078abf48fe101731362cda192ae205568d2"
  
  depends_on "git"
  depends_on "zsh"
  
  conflicts_with "svn"
  conflicts_with "bash"

  def install
    bin.install "program"
    ...
  end
end
